#!/bin/bash
#
# Geddy JavaScript Web development framework
# Copyright 2112 Matthew Eernisse (mde@fleegix.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SOURCE_DIR=
ROOT_DIR=`pwd`
DAEMON=0
COMMAND=
ARGS=
PIDPATH='./log'
PIDFILE=
ACTION="start"

while [ "$1" != "" ] 
do
  case $1 in
    -r|--geddy-root) 
                  ROOT_DIR=$2                  
	          ARGS="${ARGS}-r ${2} "
                  shift 2
                  ;; 
    -x|--server-root) 
                  SOURCE_DIR=$2
                  shift 2
                  ;; 
    -d|--daemon) 
                  DAEMON=1
                  shift
                  ;;
    --stop)
                  ACTION="stop"
                  shift
                  ;;
    *)
                  ARGS="${ARGS}${1} "
                  shift
                  ;;
  esac

done

ARGS="${ARGS}-r ${ROOT_DIR}"

if [ $ACTION = "start" ]
then
  COMMAND="/usr/local/bin/node"

  if [ -z $SOURCE_DIR ]
    then
      unset NODE_PATH; 
      COMMAND="${COMMAND} ${HOME}/.node_libraries"
    else
      export NODE_PATH=${SOURCE_DIR}; 
      COMMAND="${COMMAND} ${SOURCE_DIR}"
  fi

  COMMAND="${COMMAND}/geddy-core/scripts/startserv.js ${ARGS}"

  if [ $DAEMON = 1 ]
  then
    $COMMAND > /dev/null &
    PIDFILE="${PIDPATH}/geddy.pid"
    echo "$!" > $PIDFILE
  else
    $COMMAND
  fi
else
  PIDFILE=`echo $ROOT_DIR|sed 's/\//\-/g'`
  PIDFILE="${PIDPATH}/geddy.pid"
  if [ -s $PIDFILE ]
    then
      p=`cat $PIDFILE`
      >$PIDFILE
      if [ `kill -SIGINT "${p}"` ]
      then
        kill -9 "${p}"
        exit 1
      fi
  fi
fi
exit 0
