#!/bin/bash
#
# Geddy JavaScript Web development framework
# Copyright 2112 Matthew Eernisse (mde@fleegix.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SOURCE_DIR=""
USE_SOURCE=0

for x in $@
do
  if [ $USE_SOURCE = 1 ]
  then
    SOURCE_DIR="$x"
    break
  fi
  if [ ${x:0:13} = "--server-root" ]
  then
    USE_SOURCE=1
    # This doesn't expand ~/ paths, why not?
    SOURCE_DIR="${x/--server-root=/}"
    break
  fi
  if [ "$x" = "-x" ]
  then
    USE_SOURCE=1
  fi
done

if [ $USE_SOURCE = 0 ]
then
  unset NODE_PATH; node ~/.node_libraries/geddy-core/scripts/startserv.js -r `pwd` $@
else
  export NODE_PATH=${SOURCE_DIR}; node ${SOURCE_DIR}/geddy-core/startserv.js -r `pwd` $@
fi
