name: GitHub Actions

on:
  pull_request:
    branches:
      - main
      - version-4 # Delete this after EJS v4 is released
  push:
    branches:
      - main
      - version-4 # Delete this after EJS v4 is released

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 21
          - 22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test
